# Generated by Django 5.2 on 2025-05-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_alter_plant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
