# Generated by Django 5.2 on 2025-05-31 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_favorite_plant_favorited_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='PlantFavorite',
        ),
        migrations.AlterUniqueTogether(
            name='plantfavorite',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='plant',
            name='favorited_by',
        ),
        migrations.AddField(
            model_name='plant',
            name='favorite_users',
            field=models.ManyToManyField(related_name='favorite_plants', through='plant.PlantFavorite', through_fields=('plant', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
