# Generated by Django 5.2 on 2025-06-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_rename_favorite_plantfavorite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='care_tips',
            field=models.TextField(blank=True, default='', help_text='植物的養護技巧'),
        ),
        migrations.AddField(
            model_name='plant',
            name='growing_condition',
            field=models.TextField(blank=True, default='', help_text='植物的生長條件'),
        ),
    ]
