# Generated by Django 5.2 on 2025-06-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_plant_care_tips_plant_growing_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='growing_condition',
        ),
        migrations.AddField(
            model_name='plant',
            name='humidity',
            field=models.CharField(blank=True, default='', help_text='濕度需求', max_length=255),
        ),
        migrations.AddField(
            model_name='plant',
            name='light_requirement',
            field=models.CharField(blank=True, default='', help_text='光照需求', max_length=255),
        ),
        migrations.AddField(
            model_name='plant',
            name='temperature',
            field=models.CharField(blank=True, default='', help_text='溫度需求', max_length=255),
        ),
    ]
