# Generated by Django 5.2 on 2025-06-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0007_remove_plant_growing_condition_plant_humidity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='care_tips',
        ),
        migrations.AddField(
            model_name='plant',
            name='precaution',
            field=models.CharField(blank=True, default='', help_text='注意事項', max_length=255),
        ),
        migrations.AddField(
            model_name='plant',
            name='repotting',
            field=models.CharField(blank=True, default='', help_text='換盆建議', max_length=255),
        ),
        migrations.AddField(
            model_name='plant',
            name='watering',
            field=models.CharField(blank=True, default='', help_text='澆水頻率', max_length=255),
        ),
    ]
