# Generated by Django 5.1.6 on 2025-03-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdName', models.CharField(max_length=20)),
                ('stdSex', models.CharField(default='M', max_length=2)),
                ('stdBirthday', models.DateField()),
                ('stdEmail', models.EmailField(blank=True, max_length=100, null=True)),
                ('stdPhone', models.CharField(blank=True, max_length=50, null=True)),
                ('stdAddress', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
